---
title: "ICW Jeopardy"
resource_files:
- Import Current Jeopardy Workbook.R
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r libraries, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(gridExtra)
library(ggthemes)
library(scales)
library(zoo)
library(knitr)
library(kableExtra)
library(RColorBrewer)
library(toOrdinal)
library(shiny)
library(DT)
library(rsconnect)
library(readxl)
library(lubridate)
```



```{r include=FALSE}
source("Import Current Jeopardy Workbook.R")

RawJeopardyData <- read_excel("Jeopardy Data.xlsx" ,skip = 3)

## Reset point
JeopardyData <- RawJeopardyData

ColumnPatternRemoval <- "\\.\\.\\.|Percent|Glance|Day"
NamePatternRemoval <- " "
NameChangePattern <- "Robert"

JeopardyData <- JeopardyData[ ,!str_detect(colnames(JeopardyData) ,pattern = ColumnPatternRemoval)]

JeopardyData <- JeopardyData %>%
  filter(!is.na(Robert) | !is.na(Matt))

colnames(JeopardyData) <- str_remove_all(colnames(JeopardyData) ,pattern = NamePatternRemoval)
colnames(JeopardyData) <- str_replace_all(colnames(JeopardyData) ,pattern = NameChangePattern ,replacement = "RoBert")

JeopardyData <- JeopardyData %>%
  mutate(DayOfWeek    = wday(Date ,label = TRUE ,abbr = FALSE)
         ,JeopardyType = ifelse(Value %in% c(200 ,600 ,1000) ,"Jeopardy" ,ifelse(Value %in% c(400 ,1200 ,2000) ,"Double Jeopardy" ,"Final Jeopardy"))) %>%
  select(Week:Date ,DayOfWeek:JeopardyType ,everything()) %>%
  arrange(Date)

TidyJeopardyData <- JeopardyData %>%
  gather(key = "Player" ,value = "CorrectAnswer" ,-c(Week:Value)) %>%
  mutate(CorrectAnswerPoints = CorrectAnswer * Value)

NotEnoughQuestionsAnsweredPlayers <- TidyJeopardyData %>%
  group_by(Player) %>%
  summarise(MissingDays = sum(is.na(CorrectAnswer))) %>%
  filter(MissingDays >= 5) %>%
  select(Player) %>%
  pull()

CompleteWeeksVector <- TidyJeopardyData %>%
  filter(Player == "RoBert") %>%
  group_by(Week) %>%
  summarise(Count = n()) %>%
  filter(Count == 7) %>%
  select(Week) %>%
  pull()

WeekWinningPlayersCount <- TidyJeopardyData %>%
  filter(Week %in% CompleteWeeksVector) %>%
  group_by(Week ,Player) %>%
  summarise(MaxCorrectAnswerPoints = sum(CorrectAnswerPoints ,na.rm = TRUE)) %>%
  top_n(MaxCorrectAnswerPoints ,n=1) %>%
  ungroup() %>%
  select(Player) %>%
  pull() %>%
  table() %>%
  as_tibble()

colnames(WeekWinningPlayersCount) <- c("Player" ,"WeeksWon")

PlayerList <- TidyJeopardyData %>%
  select(Player) %>%
  unique()

WeeksWonChart <- PlayerList %>%
  left_join(WeekWinningPlayersCount ,by = "Player") %>%
  mutate(WeeksWon = ifelse(is.na(WeeksWon) ,0 ,WeeksWon))

ChartLevelsFunction <- function(Dataset ,Variable ,Player) {
  LevelVector <- Dataset %>%
    arrange(desc(Variable) ,Player) %>%
    pull(Player) %>%
    rev()
  Dataset$Player <- factor(Dataset$Player ,levels = LevelVector)
  return(Dataset)
}


WeeksWonChart <- ChartLevelsFunction(WeeksWonChart ,WeeksWonChart$WeeksWon ,WeeksWonChart$Player)

TotalPointsChart <- TidyJeopardyData %>%
  group_by(Player) %>%
  summarise(CorrectAnswerPoints = sum(CorrectAnswerPoints ,na.rm = TRUE))

TotalPointsChart <- ChartLevelsFunction(TotalPointsChart ,TotalPointsChart$CorrectAnswerPoints ,TotalPointsChart$Player)
  
TotalCorrectChart <- TidyJeopardyData %>%
  group_by(Player) %>%
  summarise(CorrectAnswer = sum(CorrectAnswer ,na.rm = TRUE))

TotalCorrectChart <- ChartLevelsFunction(TotalCorrectChart ,TotalCorrectChart$CorrectAnswer ,TotalCorrectChart$Player)

ValuesVector <- TidyJeopardyData %>%
  select(Value) %>%
  unique() %>%
  arrange(Value) %>%
  pull()

LongestWrongStreakChart <- TidyJeopardyData %>%
  group_by(Player) %>%
  summarise(LongestWrongStreak = max(rle(CorrectAnswer == 0)[[1]][rle(CorrectAnswer == 1)[[2]] == 0])
            ,CurrentWrongStreak = ifelse(rle(CorrectAnswer)$values[length(rle(CorrectAnswer)$values)] == 0 ,0 ,rle(CorrectAnswer)$lengths[length(rle(CorrectAnswer)$lengths)])
            ) %>%
  filter(!is.na(LongestWrongStreak)) %>%
  arrange(desc(LongestWrongStreak) ,Player)

LongestWrongStreakChart <- ChartLevelsFunction(LongestWrongStreakChart ,LongestWrongStreakChart$LongestWrongStreak ,LongestWrongStreakChart$Player)

LongestCorrectStreakChart <- TidyJeopardyData %>%
  filter(!is.na(CorrectAnswer)) %>%
  group_by(Player) %>%
  summarise(LongestCorrectStreak = max(rle(CorrectAnswer == 1)[[1]][rle(CorrectAnswer == 0)[[2]] == 0])) %>%
  filter(!is.na(LongestCorrectStreak)) %>%
  arrange(desc(LongestCorrectStreak) ,Player)

LongestWrongStreakChart <- ChartLevelsFunction(LongestWrongStreakChart ,LongestWrongStreakChart$LongestWrongStreak ,LongestWrongStreakChart$Player)

StreakData <- TidyJeopardyData %>%  
    filter(!is.na(CorrectAnswer)) %>%
    group_by(Player) %>%
    summarise(LongestWrongStreak    = max(rle(CorrectAnswer)$lengths[rle(CorrectAnswer)$values==0])
              ,LongestCorrectStreak = max(rle(CorrectAnswer)$lengths[rle(CorrectAnswer)$values==1])
              ,CurrentWrongStreak   = ifelse(rle(CorrectAnswer)$values[length(rle(CorrectAnswer)$values)]==0 ,rle(CorrectAnswer)$lengths[rle(CorrectAnswer)$values==0][length(rle(CorrectAnswer)$lengths[rle(CorrectAnswer)$values==0])] ,0)
              ,CurrentCorrectStreak = ifelse(rle(CorrectAnswer)$values[length(rle(CorrectAnswer)$values)]==1 ,rle(CorrectAnswer)$lengths[rle(CorrectAnswer)$values==1][length(rle(CorrectAnswer)$lengths[rle(CorrectAnswer)$values==1])] ,0)
              )

StreakChartData <- StreakData %>%
  gather(key = "StreakType" ,value = "Streak" ,-Player) %>%
  mutate(CorrectFlag = ifelse(str_detect(StreakType ,pattern = "Correct") ,"Correct" ,"Incorrect")
         ,LengthType = ifelse(str_detect(StreakType ,pattern = "Longest") ,"Longest" ,"Current")
         ) %>%
  select(Player:StreakType ,CorrectFlag:LengthType ,Streak)
 
StreakChartData$LengthType <- factor(StreakChartData$LengthType ,levels = c("Longest" ,"Current"))


UnansweredQuestionsChart <- TidyJeopardyData %>%
  group_by(Player) %>%
  summarise(UnansweredQuestions = sum(is.na(CorrectAnswer))) %>%
  arrange(desc(UnansweredQuestions))

UnansweredQuestionsChart <- ChartLevelsFunction(UnansweredQuestionsChart ,UnansweredQuestionsChart$UnansweredQuestions ,UnansweredQuestionsChart$Player)

ThreeDayCategories <- TidyJeopardyData %>%
  filter(Player == "RoBert") %>%
  group_by(Category) %>%
  summarise(TotalQuestions = n()) %>%
  filter(TotalQuestions == 3) %>%
  select(Category) %>%
  pull()

BestCategoriesChart <- TidyJeopardyData %>%
  filter(Category %in% ThreeDayCategories) %>%
  group_by(Category) %>%
  summarise(TotalCorrect = sum(CorrectAnswer ,na.rm = T)
            ,TotalPoints = sum(CorrectAnswerPoints ,na.rm = T)) %>%
  arrange(desc(TotalCorrect) ,Category) %>%
  slice(1:5)

WorstCategoriesChart <- TidyJeopardyData %>%
  filter(Category %in% ThreeDayCategories) %>%
  group_by(Category) %>%
  summarise(TotalCorrect = sum(CorrectAnswer ,na.rm = T)
            ,TotalPoints = sum(CorrectAnswerPoints ,na.rm = T)) %>%
  arrange(TotalCorrect ,Category) %>%
  slice(1:5)

BestCategoriesLevels <- BestCategoriesChart %>%
  select(Category) %>%
  pull()

WorstCategoriesLevels <- WorstCategoriesChart %>%
  select(Category) %>%
  pull()

BestCategoriesChart$Category <- factor(BestCategoriesChart$Category ,levels = rev(BestCategoriesLevels))
WorstCategoriesChart$Category <- factor(WorstCategoriesChart$Category ,levels = rev(WorstCategoriesLevels))

PlayerListVector <- TidyJeopardyData %>%
  select(Player) %>%
  unique() %>%
  pull()

NewSimilarityColumns <- str_c("SameAs" ,PlayerListVector)

SelectedJeopardyData <- JeopardyData %>%
  select(Date ,PlayerListVector)

TidyJeopardyData <- TidyJeopardyData %>%
  left_join(SelectedJeopardyData ,by = "Date")

for (i in 1:length(NewSimilarityColumns)) {
  TidyJeopardyData <- TidyJeopardyData %>%
    mutate(!!NewSimilarityColumns[i] := as.numeric(coalesce(CorrectAnswer ,-1)==coalesce(.[[!!PlayerListVector[i]]] ,-1)))
}

PlayerSimilarityData <- TidyJeopardyData %>%
  gather(key = "Competitor" ,value = "SameAnswer" ,NewSimilarityColumns) %>%
  mutate(Competitor = str_remove(Competitor ,pattern = "SameAs")) %>%
  filter(Player != Competitor)

PlayerSimilarityChart <- PlayerSimilarityData %>%
  group_by(Player ,Competitor) %>%
  summarise(PercentSimilarity = sum(SameAnswer) / n())

TopPlayer <- TidyJeopardyData %>%
  group_by(Player) %>%
  summarise(TotalCorrect = sum(CorrectAnswer)
            ,TotalPoints = sum(CorrectAnswerPoints)) %>%
  arrange(desc(TotalCorrect) ,desc(TotalPoints) ,Player) %>%
  select(Player) %>%
  slice(1) %>%
  pull()

ValueChart <- TidyJeopardyData %>%
  group_by(Player ,Value) %>%
  summarise(CorrectAnswer = sum(CorrectAnswer ,na.rm = TRUE))

ValueLevelsVector <- ValueChart %>%
  ungroup() %>%
  select(Value) %>%
  arrange(desc(Value)) %>%
  unique() %>%
  pull()

ValueChart$Value <- factor(ValueChart$Value ,levels = ValueLevelsVector)

PercentCorrectChart <- TidyJeopardyData %>%
  group_by(Player) %>%
  summarise(PercentCorrect = sum(CorrectAnswer ,na.rm = TRUE)/sum(!is.na(CorrectAnswer)))

PercentCorrectLevels <- PercentCorrectChart %>%
  arrange(PercentCorrect ,desc(Player)) %>%
  select(Player) %>%
  pull()

PercentCorrectChart$Player <- factor(PercentCorrectChart$Player ,levels = PercentCorrectLevels)

PointsOverTimeData <- TidyJeopardyData %>%
  group_by(Player) %>%
  mutate(CumulativePoints = cumsum(coalesce(CorrectAnswerPoints ,0))) %>%
  select(Date ,Player ,CorrectAnswerPoints ,CumulativePoints) 

DateVector <- PointsOverTimeData %>%
  ungroup() %>%
  select(Date) %>%
  arrange(Date) %>%
  unique() %>%
  pull()

IdVector <- seq(from = 1 ,to = length(DateVector) ,by = 1)

IdTable <- tibble(
  Id = IdVector
  ,Date = DateVector
)

PointsOverTimeData <- PointsOverTimeData %>%
  left_join(IdTable ,by = "Date") %>%
  select(Id ,everything())

TotalQuestions <- max(PointsOverTimeData$Id)
TotalCategories <- TidyJeopardyData %>%
  select(Category) %>%
  unique() %>%
  summarise(CategoryCount = n()) %>%
  pull()

TopPointsOverTime <- PointsOverTimeData %>%
  group_by(Id) %>%
  summarise(Leader = max(CumulativePoints))

LeaderPointsData <- PointsOverTimeData %>%
  left_join(TopPointsOverTime ,by = "Id") %>%
  mutate(InLead = as.numeric(CumulativePoints==Leader)) %>%
  group_by(Player) %>%
  summarise(QuestionsAsLeader = sum(InLead))
  
CategoryTable <- TidyJeopardyData %>%
  group_by(Player ,Category) %>%
  summarise(`Correct Answers`  = sum(CorrectAnswer ,na.rm = TRUE)
            ,`Total Questions` = n()
            ,`Points Earned`   = sum(CorrectAnswerPoints ,na.rm = TRUE)
            ,`Points Possible` = sum(Value)
            ) %>%
  arrange(Player ,desc(`Correct Answers`) ,desc(`Points Earned`))

```


Leaderboard
=======================================================================

Column {data-width=200 .sidebar}
-----------------------------------------------------------------------

### Filters

```{r}

selectInput("Value"
            ,"Select a question value:"
            ,choices = ValuesVector
            ,multiple = TRUE
            ,selected = ValuesVector)

```


Column {data-width=450}
-----------------------------------------------------------------------


### Total Points

```{r}

TidyJeopardyData2 <- TidyJeopardyData

ReverseAlphabeticalLevels <- TidyJeopardyData2 %>%
  select(Player) %>%
  unique() %>%
  arrange(desc(Player)) %>%
  pull()

TidyJeopardyData2$Player <- factor(TidyJeopardyData2$Player ,levels = ReverseAlphabeticalLevels)

ReactiveTotalPointsData <- reactive({
  TidyJeopardyData2 %>%
    filter(Value %in% input$Value) %>%
    group_by(Player) %>%
    summarise(CorrectAnswerPoints = sum(CorrectAnswerPoints ,na.rm = TRUE)) %>%
    arrange(desc(CorrectAnswerPoints) ,Player)
})


renderPlot({
  ggplot(ReactiveTotalPointsData() ,aes(x = reorder(Player ,CorrectAnswerPoints ,FUN = function(x) {x}) ,y = CorrectAnswerPoints)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = comma ,breaks = pretty_breaks()) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen")) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight() +
    theme(legend.position = "none")
})

```

### Correct Answers

```{r}

ReactiveTotalCorrectData <- reactive({
  TidyJeopardyData2 %>%
    filter(Value %in% input$Value) %>%
    group_by(Player) %>%
    summarise(CorrectAnswer = sum(CorrectAnswer ,na.rm = TRUE)) %>%
    arrange(desc(CorrectAnswer) ,Player)
})

renderPlot({
  ggplot(ReactiveTotalCorrectData() ,aes(x = reorder(Player ,CorrectAnswer ,FUN = function(x) {x}) ,y = CorrectAnswer)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = comma ,breaks = pretty_breaks()) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(MinTeammatePlusMinus ,MaxTeammatePlusMinus)) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight() 
})



```

Column {data-width=350}
-----------------------------------------------------------------------

### Total Questions

```{r}

valueBox(TotalQuestions, icon = "far fa-calendar-alt")

```


### Weeks Won

```{r}

renderPlot({
ggplot(WeeksWonChart ,aes(x = Player ,y = WeeksWon)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = comma ,breaks = pretty_breaks()) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(MinTeammatePlusMinus ,MaxTeammatePlusMinus)) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight()   
})

```

### Points over Time

```{r}

renderPlot({
  ggplot(PointsOverTimeData ,aes(x = Id ,y = CumulativePoints ,color = Player)) +
    geom_line(alpha = .64 ,size = 1) +
    # coord_flip() +
    scale_y_continuous(labels = scales::comma ,breaks = pretty_breaks()) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(MinTeammatePlusMinus ,MaxTeammatePlusMinus)) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight() 
})


```


Other Statistics
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Total Categories

```{r}

valueBox(TotalCategories ,icon = "fas fa-question-circle")

```


### Correct Streak

```{r}
CorrectStreakData <- StreakChartData %>% 
  filter(CorrectFlag == "Correct")

CorrectPlayerLevels <- CorrectStreakData %>%
  filter(LengthType == "Longest") %>%
  group_by(Player) %>%
  summarise(MaxStreak = max(Streak)) %>%
  arrange(MaxStreak ,desc(Player)) %>%
  select(Player) %>%
  pull()

CorrectStreakData$Player <- factor(CorrectStreakData$Player ,levels = CorrectPlayerLevels)

renderPlot({
ggplot(CorrectStreakData ,aes(x = Player ,y = Streak)) +
    geom_col() +
    coord_flip() +
    facet_wrap(. ~ LengthType) +
    scale_y_continuous(labels = comma ,breaks = pretty_breaks()) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(MinTeammatePlusMinus ,MaxTeammatePlusMinus)) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight() 
})

```

### Incorrect Streak

```{r}
IncorrectStreakData <- StreakChartData %>% 
  filter(CorrectFlag == "Incorrect")

IncorrectPlayerLevels <- IncorrectStreakData %>%
  filter(LengthType == "Longest") %>%
  group_by(Player) %>%
  summarise(MaxStreak = max(Streak)) %>%
  arrange(MaxStreak ,desc(Player)) %>%
  select(Player) %>%
  pull()

IncorrectStreakData$Player <- factor(IncorrectStreakData$Player ,levels = IncorrectPlayerLevels)

renderPlot({
ggplot(IncorrectStreakData ,aes(x = Player ,y = Streak)) +
    geom_col() +
    coord_flip() +
    facet_wrap(. ~ LengthType) +
    scale_y_continuous(labels = comma ,breaks = pretty_breaks()) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(MinTeammatePlusMinus ,MaxTeammatePlusMinus)) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight() 
})

```

Column {data-width=500}
-----------------------------------------------------------------------


### Best Categories as Group (3 day categories only)

```{r}


renderPlot({
ggplot(BestCategoriesChart ,aes(x = Category ,y = TotalCorrect)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = comma ,breaks = pretty_breaks()) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen")) +
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight()   
})



```


### Worst Categories as Group (3 day categories only)

```{r}

renderPlot({
ggplot(WorstCategoriesChart ,aes(x = Category ,y = TotalCorrect)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = comma ,breaks = pretty_breaks()) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(MinTeammatePlusMinus ,MaxTeammatePlusMinus)) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight()   
})


```

### Percent Correct

```{r}

MinPercentCorrect <- PercentCorrectChart %>%
  summarise(MinPercentCorrect = min(PercentCorrect)) %>%
  pull()

MaxPercentCorrect <- PercentCorrectChart %>%
  summarise(MinPercentCorrect = max(PercentCorrect)) %>%
  pull()

renderPlot({
ggplot(PercentCorrectChart ,aes(x = Player ,y = PercentCorrect)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = scales::percent ,breaks = c(0 ,.25 ,.5 ,.75 ,1) ,limit = c(0 ,1)) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(MinPercentCorrect ,MaxPercentCorrect)) +
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight() +
    theme(legend.position = "none") 
})


```

Player Page
=======================================================================

Column {data-width=200 .sidebar}
-----------------------------------------------------------------------

### Filters

```{r}

selectInput("Player"
            ,"Select a player:"
            ,choices = arrange(PlayerList ,Player)
            ,selected = TopPlayer)


```

Column {data-width=450}
-----------------------------------------------------------------------

### Unanswered Questions

```{r}

ReactiveUnanswered <- reactive({
  UnansweredQuestionsChart %>%
    filter(Player == input$Player) %>%
    select(UnansweredQuestions) %>%
    pull()
})

renderValueBox(
  valueBox(ReactiveUnanswered()
           ,icon = "fas fa-calendar-check"
           ,color = ifelse(ReactiveUnanswered() == 0, "success", ifelse(ReactiveUnanswered() < 8 ,"warning" ,"danger")))
)


```

### Player Similarity

```{r}

PlayerSimilarityChart$Competitor <- factor(PlayerSimilarityChart$Competitor ,levels = ReverseAlphabeticalLevels)

ReactiveSimilarityData <- reactive({
  PlayerSimilarityChart %>%
    filter(Player %in% input$Player)
})

renderPlot({
  ggplot(ReactiveSimilarityData() ,aes(x = reorder(Competitor ,PercentSimilarity ,FUN = function(x) {x}) ,y = PercentSimilarity)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = scales::percent ,breaks = c(0 ,.25 ,.5 ,.75 ,1) ,limits = c(0 ,1)) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(MinTeammatePlusMinus ,MaxTeammatePlusMinus)) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight() 
})


```


Column {data-width=350}
-----------------------------------------------------------------------

### Number of Questions while in the Lead

```{r}

ReactiveLeaderData <- reactive({
  LeaderPointsData %>%
    filter(Player == input$Player) %>%
    select(QuestionsAsLeader) %>%
    pull()
})

ExpectedDaysInLead <- TotalQuestions / length(PlayerListVector)

renderValueBox(
  valueBox(ReactiveLeaderData()
           ,icon = "fas fa-trophy"
           ,color = ifelse(ReactiveLeaderData() == 0, "danger", ifelse(ReactiveLeaderData() < ExpectedDaysInLead ,"warning" ,"success")))
)


```

### Correct Percent

```{r}

ReactiveCorrectPercent <- reactive({
  PercentCorrectChart %>%
    filter(Player == input$Player) %>%
    mutate(PercentCorrect = round(PercentCorrect * 100 ,1))%>%
    select(PercentCorrect) %>%
    pull()
})


LowerPercentile <- floor(quantile(PercentCorrectChart$PercentCorrect ,1/3) * 100)
UpperPercentile <- floor(quantile(PercentCorrectChart$PercentCorrect ,2/3) * 100)

renderGauge({
  gauge(ReactiveCorrectPercent() 
        ,min = 0 
        ,max = 100 
        ,symbol = '%'
        ,sectors = gaugeSectors(success = c(UpperPercentile ,100) ,warning = c(LowerPercentile ,UpperPercentile) ,danger = c(0 ,LowerPercentile)))
})

```

### Correct Answers by Value

```{r}

ReactiveValueData <- reactive({
 ValueChart %>%
    filter(Player %in% input$Player)
})

renderPlot({
  ggplot(ReactiveValueData() ,aes(x = Value ,y = CorrectAnswer)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = scales::comma ,breaks = pretty_breaks()) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(MinTeammatePlusMinus ,MaxTeammatePlusMinus)) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight() 
})

```

### Performance by Category 

```{r}


DT::renderDataTable({
  CategoryTable2 <- CategoryTable %>%
    filter(Player %in% input$Player) %>%
    ungroup() %>%
    select(-Player)
  DT::datatable(CategoryTable2 ,options = list(scrollY = '300px', paging = FALSE, scrollX = TRUE))
})



```

